### ISSUE TITLE
Improvements to Theme

### ISSUE THREAD

**Issue by nabobalis** [DuyguKeskek/sunpy-website#1]
- [x] Larger sunpy logo. 
- [x] Removal of bottom bar
- [x]  Small Screen, logo is covered by search bar. ( Remove Searchbox)
- [x] Text Orange is not the same as the logo orange.
- [x] Top left SunPy should be loser cases
- [x] All the text could do with being a little bigger
- [x] the main "sunpy" under the logo should be notably bigger
- [x] there is no mouseover style on the buttons on the main page
- [x] the side menu the mouse over colour should be less saturated
- [ ] The mouseover colour on the sunpy in the top left is wrong
- [ ] the sunpy in the top left should be the same font and colours as the logo
- [ ] Sidebar titles for the Blog are off center

**Comment by nabobalis** [comment]
According to gimp the sunpy logo has #fe7900 while the orange on the website is #ff5722.

**Comment by DuyguKeskek** [comment]
I also changed this blue black color to Dark Gray #444444 . Everything above is done.

**Comment by nabobalis** [comment]
Thanks, I just built the site. It looks fine to me. 

I will close this issue, I will reopen it if something else comes up!

**Comment by nabobalis** [comment]
- [ ] The mouseover colour on the sunpy in the top left is wrong
- [ ] the sunpy in the top left should be the same font and colours as the logo
- [ ] All the text could do with being a little bigger
- [ ] the main "sunpy" under the logo should be notably bigger
- [ ] there is no mouseover style on the buttons on the main page
- [ ] the side menu the mouse over colour should be less saturated

**Comment by DuyguKeskek** [comment]
I corrected the hover color on the top left sunpy, but couldn't seperate the navbar title into two parts to use different colors. It should be handled using Jinja but I couldn't manage it yet. I can turn back to this later, since there are more important issues waiting for me.
