### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by nabobalis** [DuyguKeskek/sunpy-website#6]
Since we want a blog (I wonder if it would even be used, the last one wasn't). We need to figure out the best method for this. Ablog is what we want. We want a sphinx extension we can add to the website. Problem is that Ablog is broken.

Either we get commit rights to the main repo or we have maintain a fork of Ablog until it becomes unnecessary to do so. 

If we maintain a fork of ablog, we will need to add that manually  to the travis build.

**Comment by DuyguKeskek** [comment]
@nabobalis I think we can close the issue.

**Comment by nabobalis** [comment]
Yes we can.
